/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectoautomatas;

/**
 *
 * @author iv4nt
 */
public class InterfazAutomata extends javax.swing.JFrame {
    
    private static AutomataPrincipal automata;
    /**
     * Creates new form InterfazAutomata
     */
    public InterfazAutomata() {
	setDefaultCloseOperation(EXIT_ON_CLOSE);
	automata = new AutomataPrincipal("./src/main/java/com/mycompany/proyectoautomatas/tokens.txt");
	automata.evaluarTexto();
	//Después de aplicar el autómata e iniciar los componentes visuales mostramos los resultados en la interfaz:
	initComponents();
	labelComentarios.setText("Comentarios: " + automata.getContadorComentarios());
	labelEnteros.setText("Números Enteros: " + automata.getContadorEnteros());
	labelDecimales.setText("Números Decimales: " + automata.getContadorFlotantes());
	labelParentesis.setText("Paréntesis: " + automata.getContadorParentesis());
        labelLlaves.setText("Llaves: " + automata.getContadorLlaves());
        labelAsignaciones.setText("Asignaciones: " + automata.getContadorAsignacion());
	labelRelacionales.setText("Operadores Relacionales: " + automata.getContadorRelacional());
	labelAritmeticos.setText("Operadores Aritméticos: " + automata.getContadorAritmetico());
	labelLogicos.setText("Operadores Lógicos: " + automata.getContadorLogico());
	labelNulos.setText("Errores: " + automata.getContadorNulos());
	labelIdentificadores.setText("Identificadores: " + automata.getContadorIdentificadores());
	labelReservadas.setText("Palabras Reservadas: " + automata.getContadorPalabrasReservadas());
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        labelReservadas = new javax.swing.JLabel();
        labelIdentificadores = new javax.swing.JLabel();
        labelRelacionales = new javax.swing.JLabel();
        labelLogicos = new javax.swing.JLabel();
        labelAritmeticos = new javax.swing.JLabel();
        labelAsignaciones = new javax.swing.JLabel();
        labelEnteros = new javax.swing.JLabel();
        labelDecimales = new javax.swing.JLabel();
        labelComentarios = new javax.swing.JLabel();
        labelParentesis = new javax.swing.JLabel();
        labelLlaves = new javax.swing.JLabel();
        labelNulos = new javax.swing.JLabel();

        jLabel8.setText("Palabras Reservadas:");

        jLabel9.setText("Identificadores:");

        jLabel16.setText("Palabras Reservadas:");

        jLabel17.setText("Identificadores:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("JetBrainsMonoMedium NF", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Identificador de Tokens");

        jLabel2.setFont(new java.awt.Font("JetBrainsMonoMedium NF", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Texto de Entrada");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("JetBrainsMonoMedium NF", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Contadores");

        labelReservadas.setFont(new java.awt.Font("JetBrainsMonoMedium NF", 0, 10)); // NOI18N
        labelReservadas.setText("Palabras Reservadas:");

        labelIdentificadores.setFont(new java.awt.Font("JetBrainsMonoMedium NF", 0, 10)); // NOI18N
        labelIdentificadores.setText("Identificadores:");

        labelRelacionales.setFont(new java.awt.Font("JetBrainsMonoMedium NF", 0, 10)); // NOI18N
        labelRelacionales.setText("Operadores Relacionales:");

        labelLogicos.setFont(new java.awt.Font("JetBrainsMonoMedium NF", 0, 10)); // NOI18N
        labelLogicos.setText("Operadores Lógicos:");

        labelAritmeticos.setFont(new java.awt.Font("JetBrainsMonoMedium NF", 0, 10)); // NOI18N
        labelAritmeticos.setText("Operadores Aritmétics:");

        labelAsignaciones.setFont(new java.awt.Font("JetBrainsMonoMedium NF", 0, 10)); // NOI18N
        labelAsignaciones.setText("Asignaciones:");

        labelEnteros.setFont(new java.awt.Font("JetBrainsMonoMedium NF", 0, 10)); // NOI18N
        labelEnteros.setText("Números Enteros:");

        labelDecimales.setFont(new java.awt.Font("JetBrainsMonoMedium NF", 0, 10)); // NOI18N
        labelDecimales.setText("Números Decimales:");

        labelComentarios.setFont(new java.awt.Font("JetBrainsMonoMedium NF", 0, 10)); // NOI18N
        labelComentarios.setText("Comentarios:");

        labelParentesis.setFont(new java.awt.Font("JetBrainsMonoMedium NF", 0, 10)); // NOI18N
        labelParentesis.setText("Paréntesis");

        labelLlaves.setFont(new java.awt.Font("JetBrainsMonoMedium NF", 0, 10)); // NOI18N
        labelLlaves.setText("Llaves:");

        labelNulos.setFont(new java.awt.Font("JetBrainsMonoMedium NF", 0, 10)); // NOI18N
        labelNulos.setText("Paréntesis");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(labelReservadas, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(labelRelacionales, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelAritmeticos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelEnteros, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelComentarios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelLlaves, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelIdentificadores, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelLogicos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelAsignaciones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelDecimales, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelParentesis, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNulos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelReservadas)
                    .addComponent(labelIdentificadores))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRelacionales)
                    .addComponent(labelLogicos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAritmeticos)
                    .addComponent(labelAsignaciones))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEnteros)
                    .addComponent(labelDecimales))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelParentesis)
                    .addComponent(labelComentarios, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLlaves)
                    .addComponent(labelNulos))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

	
	java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
		new InterfazAutomata().setVisible(true);
	    }
	});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelAritmeticos;
    private javax.swing.JLabel labelAsignaciones;
    private javax.swing.JLabel labelComentarios;
    private javax.swing.JLabel labelDecimales;
    private javax.swing.JLabel labelEnteros;
    private javax.swing.JLabel labelIdentificadores;
    private javax.swing.JLabel labelLlaves;
    private javax.swing.JLabel labelLogicos;
    private javax.swing.JLabel labelNulos;
    private javax.swing.JLabel labelParentesis;
    private javax.swing.JLabel labelRelacionales;
    private javax.swing.JLabel labelReservadas;
    // End of variables declaration//GEN-END:variables
}
